name: budget_mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  socket_io_client: ^2.0.1
  provider: ^6.0.5 # for State management
  http: ^0.13.5
  intrinsic_grid_view: ^0.0.2
  confirm_dialog: ^1.0.1
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  simple_radio_group: ^1.0.0
  flutter_qr_bar_scanner: ^3.0.2
  flutter_money: ^0.0.3
  file_picker: ^6.1.1
  dio: ^5.4.0
  flutter_cached_pdfview: ^0.4.2
  url_launcher: ^6.2.5

  #flutter_masked_text: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/banners/
    - assets/icons/
    - assets/files/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
